"""Added recurring_id

Revision ID: 1fe857354a39
Revises: bc0b7b7445fe
Create Date: 2025-04-18 14:50:55.062865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe857354a39'
down_revision = 'bc0b7b7445fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('recurring_id')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('recurring_id')

    # ### end Alembic commands ###
