"""Add name field to User

Revision ID: 499deafba85d
Revises: 
Create Date: 2025-04-22 16:33:16.907436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499deafba85d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, server_default='User'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
