"""Add recurring transactions model

Revision ID: bc0b7b7445fe
Revises: f074caacbe55
Create Date: 2025-04-06 22:35:48.000172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0b7b7445fe'
down_revision = 'f074caacbe55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
